name: kabuk
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

workspace:
  - packages/schema

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  http: ^0.13.3
  schema: ^0.0.1
  kabuk: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.7
  build: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - asset/

